Feat/issue-29
memocode-dev/memocode_memo_server pull request #32
Opened 2024-03-23 03:11 UTC by leebuwon

### ✨ 작업 내용
---

- [ ] 부모 댓글 삭제 할 경우 대댓글 같이 삭제(변경감지)
- [ ] 게시글 댓글 조회 카운트 버그 수정
- [ ] authorId로 블로그 조회하기

### ✨ 참고 사항
---

1, 부모 댓글 삭제
forEach로 하나씩 변경 감지 시켜주었습니다. (다른 좋은 방법 있으면 추천부탁드립니다.)
```java
        // 자식 댓글또한 연쇄 삭제
        comment.getChildComments().forEach(Comment::delete);
```

### ⏰ 현재 버그
---

### ✏ Git Close
---

close #29

2024-03-23 08:55 UTC, audgks5551 requested changes
코드 작성하느라 고생하셨습니다!
코맨트를 확인하시고 수정부탁드립니다 :)

2024-03-23 08:55 UTC, audgks5551 commented on src/main/java/dev/memocode/memo_server/domain/memo/entity/Memo.java
> +    private List<Comment> comments = new ArrayList<>();
이부분에 `@Builder.Default`를 추가해주세요!
생성과 동시에 댓글을 넣는 경우는 없지만 Null예외가 나지 않기 위함입니다

2024-03-23 08:55 UTC, audgks5551 commented on src/main/java/dev/memocode/memo_server/domain/memo/repository/MemoRepositoryCustom.java
> +    Page<Memo> findByAuthorIdAndPosts(UUID authorId, Pageable pageable);
메서드 이름이 `findAllPostByAuthorId`가 더 적합해보입니다.
작성해주신 `findByAuthorIdAndPosts` 메서드는 AuthorId and Posts로 posts가 where조건에 들어가는 것처럼 해석됩니다.

2024-03-23 08:55 UTC, audgks5551 commented on src/main/java/dev/memocode/memo_server/domain/memo/repository/MemoRepositoryCustom.java
>      List<Memo> findByAuthorIdAndBookmarked(UUID authorId);
`findByAuthorIdAndBookmarked` 메서드에서 bookmarked에 대한 처리를 서비스에서 선택해서 진행될 수 있도록 수정해주세요
비즈니스로직이 repository에 들어가는 것이 좋지 않습니다.

2024-03-23 08:55 UTC, audgks5551 commented on src/main/java/dev/memocode/memo_server/domain/memo/repository/impl/MemoRepositoryImpl.java
> +                .where(memo.visibility.eq(true), memo.author.id.eq(authorId))
위에서와 동일하게 `memo.visibility.eq(true)` 이 부분을 고정하는 것이 아닌 매개변수에서 받게 하여 서비스에서 컨트롤할 수 있게 해주세요.

2024-03-23 08:55 UTC, audgks5551 commented on src/main/java/dev/memocode/memo_server/domain/memo/repository/impl/MemoRepositoryImpl.java
> +                .where(memo.visibility.eq(true), memo.author.id.eq(authorId));
이하 동문입니다

2024-03-23 08:55 UTC, audgks5551 commented on src/main/java/dev/memocode/memo_server/domain/memo/service/PostService.java
> +    public Page<PostAuthorDTO> findAuthorAllPost(UUID authorId, int page, int size) {
메서드 이름이 findAuthorAllPost 보다 findAllPostByAuthorId가 더 적합해보입니다.

2024-03-23 08:55 UTC, audgks5551 commented on src/main/java/dev/memocode/memo_server/domain/memocomment/repository/impl/CommentRepositoryImpl.java
> +                .where(comment.memo.id.eq(memoId), comment.parentComment.isNull())
이 또한 매개변수에서 처리될 수 있도록 해주세요

2024-03-23 08:55 UTC, audgks5551 commented on src/main/java/dev/memocode/memo_server/domain/memocomment/service/CommentService.java
> +        comment.getChildComments().forEach(Comment::delete);
재귀적인 호출이 필요하며 `comment.getChildComments().forEach(Comment::delete);`는 delete() 메서드 안에서 수행해주셔야 하나의 삭제가 원자적으로 유지할 수 있습니다.

2024-03-23 08:55 UTC, audgks5551 commented on src/main/java/dev/memocode/memo_server/in/api/controller/PostController.java
> +        Page<PostAuthorDTO> dto = postUseCase.findAuthorAllPost(authorId, page, size);
findAuthorAllPost 메서드이름을 findAllByAuthor로 변경해주세요

2024-03-23 08:55 UTC, audgks5551 commented on src/main/java/dev/memocode/memo_server/in/api/spec/PostApi.java
> +    ResponseEntity<Page<PostAuthorDTO>> findAuthorPost(UUID authorId, int page, int size);
findAllPostByAuthor로 변경해주세요

2024-03-23 08:55 UTC, audgks5551 commented on src/test/java/dev/memocode/memo_server/usecase/CommentUseCaseTest.java
> +        UUID comments1 = commentService.createComments(comment1);
createComment로 단수를 사용해주세요

2024-03-23 08:55 UTC, audgks5551 commented on src/test/java/dev/memocode/memo_server/usecase/CommentUseCaseTest.java
> +    private CommentService commentService;
author를 제외하고 모든 요청은 UseCase를 통해서 요청해주세요
여기는 UseCase를 테스트하는 것입니다. UseCase를 불러와서 테스트해주세요

2024-03-23 08:55 UTC, audgks5551 commented on src/test/java/dev/memocode/memo_server/usecase/CommentUseCaseTest.java
> +    private PostService postService;
이것도 마찬가지입니다. 되도록 UseCase를 이용해서 테스트해주세요

2024-03-23 08:55 UTC, audgks5551 commented on src/test/java/dev/memocode/memo_server/usecase/PostUseCaseTest.java
> +    private PostService postService;
마찬가지로 UseCase 인터페이스를 불러와주세요

2024-03-23 08:55 UTC, audgks5551 commented on src/test/java/dev/memocode/memo_server/usecase/PostUseCaseTest.java
> +}
실패에 대한 케이스도 작성해주세요

2024-03-23 08:56 UTC, leebuwon commented on src/main/java/dev/memocode/memo_server/domain/memo/entity/Memo.java
> +    private List<Comment> comments = new ArrayList<>();
수정하였습니다.

2024-03-23 08:57 UTC, leebuwon commented on src/main/java/dev/memocode/memo_server/domain/memo/repository/MemoRepositoryCustom.java
> +    Page<Memo> findByAuthorIdAndPosts(UUID authorId, Pageable pageable);
수정하였습니다!

2024-03-23 09:04 UTC, leebuwon commented on src/test/java/dev/memocode/memo_server/usecase/CommentUseCaseTest.java
> +        UUID comments1 = commentService.createComments(comment1);
메서드명 createComment로 수정하였습니다. (단수형으로)

2024-03-23 09:22 UTC, leebuwon commented on src/main/java/dev/memocode/memo_server/domain/memo/repository/impl/MemoRepositoryImpl.java
> +                .where(memo.visibility.eq(true), memo.author.id.eq(authorId))
수정하였습니다.

2024-03-23 09:23 UTC, leebuwon commented on src/main/java/dev/memocode/memo_server/domain/memo/repository/impl/MemoRepositoryImpl.java
> +                .where(memo.visibility.eq(true), memo.author.id.eq(authorId));
수정하였습니다.

2024-03-24 02:55 UTC, leebuwon commented on src/main/java/dev/memocode/memo_server/domain/memo/service/PostService.java
> +    public Page<PostAuthorDTO> findAuthorAllPost(UUID authorId, int page, int size) {
수정하였습니다.

2024-03-24 03:01 UTC, leebuwon commented on src/main/java/dev/memocode/memo_server/in/api/controller/PostController.java
> +        Page<PostAuthorDTO> dto = postUseCase.findAuthorAllPost(authorId, page, size);
윗 부분에서 findAllPostByAuthorId 이걸로 수정해달라고 요청하셔서 이걸로 했습니다.

2024-03-24 03:01 UTC, leebuwon commented on src/main/java/dev/memocode/memo_server/in/api/spec/PostApi.java
> +    ResponseEntity<Page<PostAuthorDTO>> findAuthorPost(UUID authorId, int page, int size);
수정하였습니다.

2024-03-24 03:18 UTC, leebuwon commented on src/main/java/dev/memocode/memo_server/domain/memocomment/service/CommentService.java
> +        comment.getChildComments().forEach(Comment::delete);
수정하였습니다.

2024-03-24 03:19 UTC, leebuwon commented on src/main/java/dev/memocode/memo_server/domain/memo/repository/MemoRepositoryCustom.java
>      List<Memo> findByAuthorIdAndBookmarked(UUID authorId);
수정하였습니다.

2024-03-24 03:25 UTC, leebuwon commented on src/test/java/dev/memocode/memo_server/usecase/CommentUseCaseTest.java
> +    private CommentService commentService;
수정하였습니다.

2024-03-24 03:25 UTC, leebuwon commented on src/test/java/dev/memocode/memo_server/usecase/CommentUseCaseTest.java
> +    private PostService postService;
수정하였습니다.

2024-03-24 03:26 UTC, leebuwon commented on src/test/java/dev/memocode/memo_server/usecase/PostUseCaseTest.java
> +    private PostService postService;
수정하였습니다.

2024-03-24 03:46 UTC, leebuwon commented on src/test/java/dev/memocode/memo_server/usecase/PostUseCaseTest.java
> +}
고생하셨습니다.

2024-03-24 04:39 UTC, audgks5551 approved these changes
너무 잘하셨습니다!
정말 고생많으셨습니다 :)

2024-03-24 04:40 UTC, merged